---
version: '3.9'

services:

  bookings-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bookings-api
    ports:
      - 8081:8080

  e2e:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    image: bookings-api-e2e
    depends_on:
      - bookings-api
